<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class AdmissionSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'registration_number' => 'REG-2026-0001',
                'full_name' => 'John Michael Smith',
                'nickname' => 'John',
                'gender' => 'Male',
                'place_of_birth' => 'New York',
                'date_of_birth' => '2005-03-15',
                'religion' => 'Christian',
                'citizen_id' => '1234567890123456',
                'phone' => '08123456789',
                'email' => 'john.smith@email.com',
                'street_address' => '123 Main Street, Apartment 4B',
                'district' => 'Manhattan',
                'regency' => 'New York City',
                'province' => 'New York',
                'postal_code' => '10001',
                'emergency_contact_name' => 'Mary Smith',
                'emergency_contact_phone' => '08123456788',
                'emergency_contact_relation' => 'Mother',
                'father_name' => 'Robert Smith',
                'mother_name' => 'Mary Smith',
                'course' => 'Computer Science',
                'status' => 'pending',
                'application_date' => '2026-01-15',
                'photo' => null,
                'documents' => null,
                'notes' => 'Interested in AI and Machine Learning',
            ],
            [
                'registration_number' => 'REG-2026-0002',
                'full_name' => 'Sarah Elizabeth Johnson',
                'nickname' => 'Sarah',
                'gender' => 'Female',
                'place_of_birth' => 'Los Angeles',
                'date_of_birth' => '2005-07-22',
                'religion' => 'Christian',
                'citizen_id' => '2345678901234567',
                'phone' => '08234567890',
                'email' => 'sarah.johnson@email.com',
                'street_address' => '456 Oak Avenue',
                'district' => 'Hollywood',
                'regency' => 'Los Angeles',
                'province' => 'California',
                'postal_code' => '90028',
                'emergency_contact_name' => 'David Johnson',
                'emergency_contact_phone' => '08234567891',
                'emergency_contact_relation' => 'Father',
                'father_name' => 'David Johnson',
                'mother_name' => 'Linda Johnson',
                'course' => 'Business Administration',
                'status' => 'approved',
                'application_date' => '2026-01-16',
                'notes' => 'Strong leadership skills',
            ],
            [
                'registration_number' => 'REG-2026-0003',
                'full_name' => 'Ahmad Rizki Pratama',
                'nickname' => 'Rizki',
                'gender' => 'Male',
                'place_of_birth' => 'Jakarta',
                'date_of_birth' => '2005-11-10',
                'religion' => 'Islam',
                'citizen_id' => '3174051011050001',
                'phone' => '08345678901',
                'email' => 'ahmad.rizki@email.com',
                'street_address' => 'Jl. Sudirman No. 123',
                'district' => 'Tanah Abang',
                'regency' => 'Jakarta Pusat',
                'province' => 'DKI Jakarta',
                'postal_code' => '10220',
                'emergency_contact_name' => 'Siti Pratama',
                'emergency_contact_phone' => '08345678902',
                'emergency_contact_relation' => 'Mother',
                'father_name' => 'Budi Pratama',
                'mother_name' => 'Siti Pratama',
                'course' => 'Information Technology',
                'status' => 'pending',
                'application_date' => '2026-01-17',
                'notes' => 'Experienced in web development',
            ],
            [
                'registration_number' => 'REG-2026-0004',
                'full_name' => 'Maria Garcia Rodriguez',
                'nickname' => 'Maria',
                'gender' => 'Female',
                'place_of_birth' => 'Madrid',
                'date_of_birth' => '2005-05-18',
                'religion' => 'Catholic',
                'phone' => '08456789012',
                'email' => 'maria.garcia@email.com',
                'street_address' => 'Calle Mayor 45',
                'district' => 'Centro',
                'regency' => 'Madrid',
                'province' => 'Madrid',
                'postal_code' => '28013',
                'emergency_contact_name' => 'Carlos Rodriguez',
                'emergency_contact_phone' => '08456789013',
                'emergency_contact_relation' => 'Father',
                'father_name' => 'Carlos Rodriguez',
                'mother_name' => 'Ana Garcia',
                'course' => 'International Relations',
                'status' => 'approved',
                'application_date' => '2026-01-18',
                'notes' => 'Fluent in Spanish, English, and French',
            ],
            [
                'registration_number' => 'REG-2026-0005',
                'full_name' => 'David Chen Wei',
                'nickname' => 'David',
                'gender' => 'Male',
                'place_of_birth' => 'Singapore',
                'date_of_birth' => '2005-09-25',
                'religion' => 'Buddhist',
                'phone' => '08567890123',
                'email' => 'david.chen@email.com',
                'street_address' => '88 Orchard Road',
                'district' => 'Orchard',
                'regency' => 'Singapore',
                'province' => 'Singapore',
                'postal_code' => '238858',
                'emergency_contact_name' => 'Lisa Chen',
                'emergency_contact_phone' => '08567890124',
                'emergency_contact_relation' => 'Mother',
                'father_name' => 'Michael Chen',
                'mother_name' => 'Lisa Chen',
                'course' => 'Engineering',
                'status' => 'rejected',
                'application_date' => '2026-01-19',
                'notes' => 'Strong mathematics background',
            ],
        ];

        // Continue with more records
        $moreData = [
            [
                'registration_number' => 'REG-2026-0006',
                'full_name' => 'Emily Rose Williams',
                'nickname' => 'Emily',
                'gender' => 'Female',
                'place_of_birth' => 'London',
                'date_of_birth' => '2005-12-03',
                'religion' => 'Christian',
                'phone' => '08678901234',
                'email' => 'emily.williams@email.com',
                'street_address' => '10 Downing Street',
                'district' => 'Westminster',
                'regency' => 'London',
                'province' => 'England',
                'postal_code' => 'SW1A 2AA',
                'emergency_contact_name' => 'James Williams',
                'emergency_contact_phone' => '08678901235',
                'emergency_contact_relation' => 'Father',
                'father_name' => 'James Williams',
                'mother_name' => 'Sophie Williams',
                'course' => 'Medicine',
                'status' => 'pending',
                'application_date' => '2026-01-20',
                'notes' => 'Aspiring doctor with volunteer experience',
            ],
            [
                'registration_number' => 'REG-2026-0007',
                'full_name' => 'Muhammad Fadhil Rahman',
                'nickname' => 'Fadhil',
                'gender' => 'Male',
                'place_of_birth' => 'Bandung',
                'date_of_birth' => '2005-04-08',
                'religion' => 'Islam',
                'citizen_id' => '3273040804050002',
                'phone' => '08789012345',
                'email' => 'fadhil.rahman@email.com',
                'street_address' => 'Jl. Dago No. 456',
                'district' => 'Coblong',
                'regency' => 'Bandung',
                'province' => 'Jawa Barat',
                'postal_code' => '40135',
                'emergency_contact_name' => 'Fatimah Rahman',
                'emergency_contact_phone' => '08789012346',
                'emergency_contact_relation' => 'Mother',
                'father_name' => 'Abdul Rahman',
                'mother_name' => 'Fatimah Rahman',
                'course' => 'Architecture',
                'status' => 'approved',
                'application_date' => '2026-01-21',
                'notes' => 'Creative and detail-oriented',
            ],
            [
                'registration_number' => 'REG-2026-0008',
                'full_name' => 'Jessica Anne Taylor',
                'nickname' => 'Jess',
                'gender' => 'Female',
                'place_of_birth' => 'Sydney',
                'date_of_birth' => '2005-08-14',
                'religion' => 'Christian',
                'phone' => '08890123456',
                'email' => 'jessica.taylor@email.com',
                'street_address' => '123 George Street',
                'district' => 'Sydney CBD',
                'regency' => 'Sydney',
                'province' => 'New South Wales',
                'postal_code' => '2000',
                'emergency_contact_name' => 'Andrew Taylor',
                'emergency_contact_phone' => '08890123457',
                'emergency_contact_relation' => 'Father',
                'father_name' => 'Andrew Taylor',
                'mother_name' => 'Rachel Taylor',
                'course' => 'Psychology',
                'status' => 'pending',
                'application_date' => '2026-01-22',
                'notes' => 'Interested in child psychology',
            ],
            [
                'registration_number' => 'REG-2026-0009',
                'full_name' => 'Kevin Park Min-ho',
                'nickname' => 'Kevin',
                'gender' => 'Male',
                'place_of_birth' => 'Seoul',
                'date_of_birth' => '2005-06-30',
                'religion' => 'Christian',
                'phone' => '08901234567',
                'email' => 'kevin.park@email.com',
                'street_address' => '789 Gangnam-daero',
                'district' => 'Gangnam-gu',
                'regency' => 'Seoul',
                'province' => 'Seoul',
                'postal_code' => '06000',
                'emergency_contact_name' => 'Park Ji-won',
                'emergency_contact_phone' => '08901234568',
                'emergency_contact_relation' => 'Mother',
                'father_name' => 'Park Sung-ho',
                'mother_name' => 'Park Ji-won',
                'course' => 'Music Production',
                'status' => 'approved',
                'application_date' => '2026-01-23',
                'notes' => 'Talented musician and producer',
            ],
            [
                'registration_number' => 'REG-2026-0010',
                'full_name' => 'Aisha Binti Abdullah',
                'nickname' => 'Aisha',
                'gender' => 'Female',
                'place_of_birth' => 'Kuala Lumpur',
                'date_of_birth' => '2005-10-12',
                'religion' => 'Islam',
                'phone' => '08012345678',
                'email' => 'aisha.abdullah@email.com',
                'street_address' => 'Jalan Ampang 234',
                'district' => 'Ampang',
                'regency' => 'Kuala Lumpur',
                'province' => 'Wilayah Persekutuan',
                'postal_code' => '50450',
                'emergency_contact_name' => 'Abdullah bin Hassan',
                'emergency_contact_phone' => '08012345679',
                'emergency_contact_relation' => 'Father',
                'father_name' => 'Abdullah bin Hassan',
                'mother_name' => 'Fatimah binti Ahmad',
                'course' => 'Islamic Studies',
                'status' => 'pending',
                'application_date' => '2026-01-24',
                'notes' => 'Strong religious background',
            ],
        ];

        $data = array_merge($data, $moreData);

        // Add 10 more records
        $additionalData = [
            [
                'registration_number' => 'REG-2026-0011',
                'full_name' => 'Daniel James Brown',
                'nickname' => 'Dan',
                'gender' => 'Male',
                'place_of_birth' => 'Chicago',
                'date_of_birth' => '2005-02-28',
                'religion' => 'Christian',
                'phone' => '08123456780',
                'email' => 'daniel.brown@email.com',
                'street_address' => '567 Michigan Avenue',
                'district' => 'Loop',
                'regency' => 'Chicago',
                'province' => 'Illinois',
                'postal_code' => '60601',
                'emergency_contact_name' => 'Susan Brown',
                'emergency_contact_phone' => '08123456781',
                'emergency_contact_relation' => 'Mother',
                'father_name' => 'Thomas Brown',
                'mother_name' => 'Susan Brown',
                'course' => 'Economics',
                'status' => 'approved',
                'application_date' => '2026-01-25',
            ],
            [
                'registration_number' => 'REG-2026-0012',
                'full_name' => 'Siti Nurhaliza Binti Ahmad',
                'nickname' => 'Siti',
                'gender' => 'Female',
                'place_of_birth' => 'Surabaya',
                'date_of_birth' => '2005-01-20',
                'religion' => 'Islam',
                'citizen_id' => '3578012001050003',
                'phone' => '08234567891',
                'email' => 'siti.nurhaliza@email.com',
                'street_address' => 'Jl. Pemuda No. 789',
                'district' => 'Genteng',
                'regency' => 'Surabaya',
                'province' => 'Jawa Timur',
                'postal_code' => '60275',
                'emergency_contact_name' => 'Ahmad bin Hassan',
                'emergency_contact_phone' => '08234567892',
                'emergency_contact_relation' => 'Father',
                'father_name' => 'Ahmad bin Hassan',
                'mother_name' => 'Aminah binti Ali',
                'course' => 'Accounting',
                'status' => 'pending',
                'application_date' => '2026-01-26',
            ],
            [
                'registration_number' => 'REG-2026-0013',
                'full_name' => 'Michael Anderson Lee',
                'nickname' => 'Mike',
                'gender' => 'Male',
                'place_of_birth' => 'Toronto',
                'date_of_birth' => '2005-07-05',
                'religion' => 'Christian',
                'phone' => '08345678902',
                'email' => 'michael.lee@email.com',
                'street_address' => '100 Queen Street West',
                'district' => 'Downtown',
                'regency' => 'Toronto',
                'province' => 'Ontario',
                'postal_code' => 'M5H 2N2',
                'emergency_contact_name' => 'Jennifer Lee',
                'emergency_contact_phone' => '08345678903',
                'emergency_contact_relation' => 'Mother',
                'father_name' => 'Robert Lee',
                'mother_name' => 'Jennifer Lee',
                'course' => 'Law',
                'status' => 'approved',
                'application_date' => '2026-01-27',
            ],
            [
                'registration_number' => 'REG-2026-0014',
                'full_name' => 'Olivia Grace Martinez',
                'nickname' => 'Liv',
                'gender' => 'Female',
                'place_of_birth' => 'Miami',
                'date_of_birth' => '2005-11-17',
                'religion' => 'Catholic',
                'phone' => '08456789013',
                'email' => 'olivia.martinez@email.com',
                'street_address' => '234 Ocean Drive',
                'district' => 'South Beach',
                'regency' => 'Miami Beach',
                'province' => 'Florida',
                'postal_code' => '33139',
                'emergency_contact_name' => 'Carlos Martinez',
                'emergency_contact_phone' => '08456789014',
                'emergency_contact_relation' => 'Father',
                'father_name' => 'Carlos Martinez',
                'mother_name' => 'Isabella Martinez',
                'course' => 'Hospitality Management',
                'status' => 'pending',
                'application_date' => '2026-01-28',
            ],
            [
                'registration_number' => 'REG-2026-0015',
                'full_name' => 'Ryan Christopher Davis',
                'nickname' => 'Ryan',
                'gender' => 'Male',
                'place_of_birth' => 'Boston',
                'date_of_birth' => '2005-03-22',
                'religion' => 'Christian',
                'phone' => '08567890124',
                'email' => 'ryan.davis@email.com',
                'street_address' => '456 Beacon Street',
                'district' => 'Back Bay',
                'regency' => 'Boston',
                'province' => 'Massachusetts',
                'postal_code' => '02115',
                'emergency_contact_name' => 'Patricia Davis',
                'emergency_contact_phone' => '08567890125',
                'emergency_contact_relation' => 'Mother',
                'father_name' => 'William Davis',
                'mother_name' => 'Patricia Davis',
                'course' => 'Biomedical Engineering',
                'status' => 'approved',
                'application_date' => '2026-01-29',
            ],
            [
                'registration_number' => 'REG-2026-0016',
                'full_name' => 'Dewi Lestari Putri',
                'nickname' => 'Dewi',
                'gender' => 'Female',
                'place_of_birth' => 'Yogyakarta',
                'date_of_birth' => '2005-09-09',
                'religion' => 'Islam',
                'citizen_id' => '3471090909050004',
                'phone' => '08678901235',
                'email' => 'dewi.lestari@email.com',
                'street_address' => 'Jl. Malioboro No. 321',
                'district' => 'Jetis',
                'regency' => 'Yogyakarta',
                'province' => 'DI Yogyakarta',
                'postal_code' => '55213',
                'emergency_contact_name' => 'Bambang Putri',
                'emergency_contact_phone' => '08678901236',
                'emergency_contact_relation' => 'Father',
                'father_name' => 'Bambang Putri',
                'mother_name' => 'Sri Lestari',
                'course' => 'Fine Arts',
                'status' => 'pending',
                'application_date' => '2026-01-30',
            ],
            [
                'registration_number' => 'REG-2026-0017',
                'full_name' => 'Alexander James Wilson',
                'nickname' => 'Alex',
                'gender' => 'Male',
                'place_of_birth' => 'Melbourne',
                'date_of_birth' => '2005-05-11',
                'religion' => 'Christian',
                'phone' => '08789012346',
                'email' => 'alex.wilson@email.com',
                'street_address' => '789 Collins Street',
                'district' => 'Melbourne CBD',
                'regency' => 'Melbourne',
                'province' => 'Victoria',
                'postal_code' => '3000',
                'emergency_contact_name' => 'Helen Wilson',
                'emergency_contact_phone' => '08789012347',
                'emergency_contact_relation' => 'Mother',
                'father_name' => 'George Wilson',
                'mother_name' => 'Helen Wilson',
                'course' => 'Sports Science',
                'status' => 'approved',
                'application_date' => '2026-01-31',
            ],
            [
                'registration_number' => 'REG-2026-0018',
                'full_name' => 'Sophie Claire Anderson',
                'nickname' => 'Sophie',
                'gender' => 'Female',
                'place_of_birth' => 'Paris',
                'date_of_birth' => '2005-12-25',
                'religion' => 'Catholic',
                'phone' => '08890123457',
                'email' => 'sophie.anderson@email.com',
                'street_address' => '45 Avenue des Champs-Élysées',
                'district' => '8th arrondissement',
                'regency' => 'Paris',
                'province' => 'Île-de-France',
                'postal_code' => '75008',
                'emergency_contact_name' => 'Pierre Anderson',
                'emergency_contact_phone' => '08890123458',
                'emergency_contact_relation' => 'Father',
                'father_name' => 'Pierre Anderson',
                'mother_name' => 'Marie Anderson',
                'course' => 'Fashion Design',
                'status' => 'pending',
                'application_date' => '2026-02-01',
            ],
            [
                'registration_number' => 'REG-2026-0019',
                'full_name' => 'Brandon Kyle Thompson',
                'nickname' => 'Brandon',
                'gender' => 'Male',
                'place_of_birth' => 'Seattle',
                'date_of_birth' => '2005-08-07',
                'religion' => 'Christian',
                'phone' => '08901234568',
                'email' => 'brandon.thompson@email.com',
                'street_address' => '567 Pike Street',
                'district' => 'Downtown',
                'regency' => 'Seattle',
                'province' => 'Washington',
                'postal_code' => '98101',
                'emergency_contact_name' => 'Karen Thompson',
                'emergency_contact_phone' => '08901234569',
                'emergency_contact_relation' => 'Mother',
                'father_name' => 'Mark Thompson',
                'mother_name' => 'Karen Thompson',
                'course' => 'Environmental Science',
                'status' => 'approved',
                'application_date' => '2026-02-01',
            ],
            [
                'registration_number' => 'REG-2026-0020',
                'full_name' => 'Natasha Putri Wijaya',
                'nickname' => 'Tasha',
                'gender' => 'Female',
                'place_of_birth' => 'Bali',
                'date_of_birth' => '2005-04-16',
                'religion' => 'Hindu',
                'citizen_id' => '5171041604050005',
                'phone' => '08012345679',
                'email' => 'natasha.wijaya@email.com',
                'street_address' => 'Jl. Sunset Road No. 888',
                'district' => 'Kuta',
                'regency' => 'Badung',
                'province' => 'Bali',
                'postal_code' => '80361',
                'emergency_contact_name' => 'Made Wijaya',
                'emergency_contact_phone' => '08012345680',
                'emergency_contact_relation' => 'Father',
                'father_name' => 'Made Wijaya',
                'mother_name' => 'Ketut Sari',
                'course' => 'Tourism Management',
                'status' => 'pending',
                'application_date' => '2026-02-01',
            ],
        ];

        $data = array_merge($data, $additionalData);

        // Add photo and documents fields to all records that don't have them
        $allFields = [
            'registration_number', 'full_name', 'nickname', 'gender', 'place_of_birth',
            'date_of_birth', 'religion', 'citizen_id', 'phone', 'email', 'street_address',
            'district', 'regency', 'province', 'postal_code', 'emergency_contact_name',
            'emergency_contact_phone', 'emergency_contact_relation', 'father_name',
            'mother_name', 'course', 'status', 'application_date', 'photo', 'documents', 'notes'
        ];
        
        foreach ($data as &$record) {
            foreach ($allFields as $field) {
                if (!isset($record[$field])) {
                    $record[$field] = null;
                }
            }
        }

        // Use database builder to bypass all validation
        $db = \Config\Database::connect();
        $builder = $db->table('admissions');
        
        // Add timestamps to all records
        $now = date('Y-m-d H:i:s');
        foreach ($data as &$record) {
            $record['created_at'] = $now;
            $record['updated_at'] = $now;
        }
        
        // Insert all records at once
        $builder->insertBatch($data);
        
        echo count($data) . " admission records have been seeded successfully!\n";
    }
}
