<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class InvoiceSeeder extends Seeder
{
    public function run()
    {
        $now = date('Y-m-d H:i:s');
        
        // Create 25 invoice records with varied data
        $data = [
            // Registration fees (unpaid, some overdue) - IDR amounts
            [
                'invoice_number' => 'INV-2026-0001',
                'registration_number' => 'REG-2026-0001',
                'description' => 'Biaya pendaftaran program Computer Science - Semester Spring 2026',
                'amount' => 2500000,
                'due_date' => '2026-02-15',
                'invoice_type' => 'registration_fee',
                'status' => 'unpaid',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'invoice_number' => 'INV-2026-0002',
                'registration_number' => 'REG-2026-0002',
                'description' => 'Biaya pendaftaran program Business Administration - Semester Spring 2026',
                'amount' => 2500000,
                'due_date' => '2026-01-25',
                'invoice_type' => 'registration_fee',
                'status' => 'paid',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'invoice_number' => 'INV-2026-0003',
                'registration_number' => 'REG-2026-0003',
                'description' => 'Biaya pendaftaran program Information Technology - Semester Spring 2026',
                'amount' => 2500000,
                'due_date' => '2026-01-20',
                'invoice_type' => 'registration_fee',
                'status' => 'unpaid',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'invoice_number' => 'INV-2026-0004',
                'registration_number' => 'REG-2026-0004',
                'description' => 'Biaya pendaftaran program International Relations - Semester Spring 2026',
                'amount' => 2500000,
                'due_date' => '2026-02-10',
                'invoice_type' => 'registration_fee',
                'status' => 'paid',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'invoice_number' => 'INV-2026-0005',
                'registration_number' => 'REG-2026-0005',
                'description' => 'Biaya pendaftaran program Engineering - Semester Spring 2026',
                'amount' => 2500000,
                'due_date' => '2026-01-15',
                'invoice_type' => 'registration_fee',
                'status' => 'cancelled',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // Tuition fees (mix of paid and unpaid) - IDR amounts
            [
                'invoice_number' => 'INV-2026-0006',
                'registration_number' => 'REG-2026-0002',
                'description' => 'Biaya kuliah Business Administration - Semester 1 tahun 2026',
                'amount' => 15000000,
                'due_date' => '2026-03-01',
                'invoice_type' => 'tuition_fee',
                'status' => 'unpaid',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'invoice_number' => 'INV-2026-0007',
                'registration_number' => 'REG-2026-0004',
                'description' => 'Biaya kuliah International Relations - Semester 1 tahun 2026',
                'amount' => 16000000,
                'due_date' => '2026-03-01',
                'invoice_type' => 'tuition_fee',
                'status' => 'paid',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'invoice_number' => 'INV-2026-0008',
                'registration_number' => 'REG-2026-0007',
                'description' => 'Biaya kuliah Architecture - Semester 1 tahun 2026',
                'amount' => 18000000,
                'due_date' => '2026-03-05',
                'invoice_type' => 'tuition_fee',
                'status' => 'unpaid',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'invoice_number' => 'INV-2026-0009',
                'registration_number' => 'REG-2026-0009',
                'description' => 'Biaya kuliah Music Production - Semester 1 tahun 2026',
                'amount' => 17000000,
                'due_date' => '2026-02-28',
                'invoice_type' => 'tuition_fee',
                'status' => 'paid',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'invoice_number' => 'INV-2026-0010',
                'registration_number' => 'REG-2026-0011',
                'description' => 'Biaya kuliah Economics - Semester 1 tahun 2026',
                'amount' => 14000000,
                'due_date' => '2026-03-10',
                'invoice_type' => 'tuition_fee',
                'status' => 'unpaid',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // Miscellaneous fees - IDR amounts
            [
                'invoice_number' => 'INV-2026-0011',
                'registration_number' => 'REG-2026-0001',
                'description' => 'Biaya peralatan laboratorium untuk praktikum Computer Science',
                'amount' => 3000000,
                'due_date' => '2026-02-20',
                'invoice_type' => 'miscellaneous_fee',
                'status' => 'unpaid',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'invoice_number' => 'INV-2026-0012',
                'registration_number' => 'REG-2026-0003',
                'description' => 'Biaya infrastruktur IT dan lisensi software',
                'amount' => 4000000,
                'due_date' => '2026-01-18',
                'invoice_type' => 'miscellaneous_fee',
                'status' => 'unpaid',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'invoice_number' => 'INV-2026-0013',
                'registration_number' => 'REG-2026-0006',
                'description' => 'Biaya asuransi kesehatan dan layanan medis',
                'amount' => 2000000,
                'due_date' => '2026-02-25',
                'invoice_type' => 'miscellaneous_fee',
                'status' => 'paid',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'invoice_number' => 'INV-2026-0014',
                'registration_number' => 'REG-2026-0008',
                'description' => 'Biaya keanggotaan perpustakaan dan akses sumber daya',
                'amount' => 1000000,
                'due_date' => '2026-03-01',
                'invoice_type' => 'miscellaneous_fee',
                'status' => 'unpaid',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'invoice_number' => 'INV-2026-0015',
                'registration_number' => 'REG-2026-0010',
                'description' => 'Biaya kegiatan kemahasiswaan dan organisasi',
                'amount' => 1500000,
                'due_date' => '2026-02-15',
                'invoice_type' => 'miscellaneous_fee',
                'status' => 'unpaid',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // Additional records for variety - IDR amounts
            [
                'invoice_number' => 'INV-2026-0016',
                'registration_number' => 'REG-2026-0013',
                'description' => 'Biaya pendaftaran program Law - Semester Spring 2026',
                'amount' => 2500000,
                'due_date' => '2026-02-05',
                'invoice_type' => 'registration_fee',
                'status' => 'paid',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'invoice_number' => 'INV-2026-0017',
                'registration_number' => 'REG-2026-0015',
                'description' => 'Biaya pendaftaran program Biomedical Engineering - Semester Spring 2026',
                'amount' => 2500000,
                'due_date' => '2026-01-28',
                'invoice_type' => 'registration_fee',
                'status' => 'unpaid',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'invoice_number' => 'INV-2026-0018',
                'registration_number' => 'REG-2026-0017',
                'description' => 'Biaya pendaftaran program Sports Science - Semester Spring 2026',
                'amount' => 2500000,
                'due_date' => '2026-02-12',
                'invoice_type' => 'registration_fee',
                'status' => 'paid',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'invoice_number' => 'INV-2026-0019',
                'registration_number' => 'REG-2026-0019',
                'description' => 'Biaya pendaftaran program Environmental Science - Semester Spring 2026',
                'amount' => 2500000,
                'due_date' => '2026-02-08',
                'invoice_type' => 'registration_fee',
                'status' => 'paid',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'invoice_number' => 'INV-2026-0020',
                'registration_number' => 'REG-2026-0013',
                'description' => 'Biaya kuliah Law - Semester 1 tahun 2026',
                'amount' => 20000000,
                'due_date' => '2026-03-15',
                'invoice_type' => 'tuition_fee',
                'status' => 'unpaid',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'invoice_number' => 'INV-2026-0021',
                'registration_number' => 'REG-2026-0015',
                'description' => 'Biaya kuliah Biomedical Engineering - Semester 1 tahun 2026',
                'amount' => 19000000,
                'due_date' => '2026-03-01',
                'invoice_type' => 'tuition_fee',
                'status' => 'unpaid',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'invoice_number' => 'INV-2026-0022',
                'registration_number' => 'REG-2026-0017',
                'description' => 'Biaya fasilitas olahraga dan penggunaan peralatan',
                'amount' => 5000000,
                'due_date' => '2026-02-28',
                'invoice_type' => 'miscellaneous_fee',
                'status' => 'paid',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'invoice_number' => 'INV-2026-0023',
                'registration_number' => 'REG-2026-0019',
                'description' => 'Biaya riset lapangan dan material laboratorium',
                'amount' => 6000000,
                'due_date' => '2026-03-05',
                'invoice_type' => 'miscellaneous_fee',
                'status' => 'unpaid',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'invoice_number' => 'INV-2026-0024',
                'registration_number' => 'REG-2026-0012',
                'description' => 'Biaya pendaftaran program Accounting - Semester Spring 2026',
                'amount' => 2500000,
                'due_date' => '2026-01-22',
                'invoice_type' => 'registration_fee',
                'status' => 'unpaid',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'invoice_number' => 'INV-2026-0025',
                'registration_number' => 'REG-2026-0014',
                'description' => 'Biaya pendaftaran program Hospitality Management - Semester Spring 2026',
                'amount' => 2500000,
                'due_date' => '2026-02-01',
                'invoice_type' => 'registration_fee',
                'status' => 'unpaid',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        // Use database builder to insert records
        $db = \Config\Database::connect();
        $builder = $db->table('invoices');
        
        // Insert all records at once
        $builder->insertBatch($data);
        
        echo count($data) . " invoice records have been seeded successfully!\n";
    }
}
