<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class PaymentSeeder extends Seeder
{
    public function run()
    {
        $now = date('Y-m-d H:i:s');
        
        // Create 25 payment records with varied data
        $data = [
            // Paid payments linked to invoices - IDR amounts
            [
                'registration_number' => 'REG-2026-0002',
                'invoice_id' => 2,
                'amount' => 2500000,
                'payment_method' => 'bank_transfer',
                'document_number' => 'TRF-2026-0001',
                'payment_date' => '2026-01-24',
                'receipt_file' => null,
                'status' => 'paid',
                'failure_reason' => null,
                'refund_date' => null,
                'refund_reason' => null,
                'notes' => 'Pembayaran biaya pendaftaran via transfer bank',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'registration_number' => 'REG-2026-0004',
                'invoice_id' => 4,
                'amount' => 2500000,
                'payment_method' => 'cash',
                'document_number' => 'CASH-2026-0001',
                'payment_date' => '2026-02-08',
                'receipt_file' => null,
                'status' => 'paid',
                'failure_reason' => null,
                'refund_date' => null,
                'refund_reason' => null,
                'notes' => 'Pembayaran tunai diterima di kasir',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'registration_number' => 'REG-2026-0004',
                'invoice_id' => 7,
                'amount' => 16000000,
                'payment_method' => 'bank_transfer',
                'document_number' => 'TRF-2026-0002',
                'payment_date' => '2026-02-27',
                'receipt_file' => null,
                'status' => 'paid',
                'failure_reason' => null,
                'refund_date' => null,
                'refund_reason' => null,
                'notes' => 'Pembayaran biaya kuliah Semester 1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'registration_number' => 'REG-2026-0009',
                'invoice_id' => 9,
                'amount' => 17000000,
                'payment_method' => 'bank_transfer',
                'document_number' => 'TRF-2026-0003',
                'payment_date' => '2026-02-25',
                'receipt_file' => null,
                'status' => 'paid',
                'failure_reason' => null,
                'refund_date' => null,
                'refund_reason' => null,
                'notes' => 'Pembayaran penuh biaya kuliah program Music Production',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'registration_number' => 'REG-2026-0006',
                'invoice_id' => 13,
                'amount' => 2000000,
                'payment_method' => 'cash',
                'document_number' => 'CASH-2026-0002',
                'payment_date' => '2026-02-23',
                'receipt_file' => null,
                'status' => 'paid',
                'failure_reason' => null,
                'refund_date' => null,
                'refund_reason' => null,
                'notes' => 'Pembayaran biaya asuransi kesehatan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // Pending payments
            [
                'registration_number' => 'REG-2026-0001',
                'invoice_id' => 1,
                'amount' => 500000.00,
                'payment_method' => 'bank_transfer',
                'document_number' => 'TRF-2026-0004',
                'payment_date' => '2026-02-02',
                'receipt_file' => null,
                'status' => 'pending',
                'failure_reason' => null,
                'refund_date' => null,
                'refund_reason' => null,
                'notes' => 'Awaiting bank confirmation',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'registration_number' => 'REG-2026-0003',
                'invoice_id' => 3,
                'amount' => 500000.00,
                'payment_method' => 'bank_transfer',
                'document_number' => 'TRF-2026-0005',
                'payment_date' => '2026-02-01',
                'receipt_file' => null,
                'status' => 'pending',
                'failure_reason' => null,
                'refund_date' => null,
                'refund_reason' => null,
                'notes' => 'Transfer verification in progress',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'registration_number' => 'REG-2026-0007',
                'invoice_id' => 8,
                'amount' => 4500000.00,
                'payment_method' => 'bank_transfer',
                'document_number' => 'TRF-2026-0006',
                'payment_date' => '2026-02-02',
                'receipt_file' => null,
                'status' => 'pending',
                'failure_reason' => null,
                'refund_date' => null,
                'refund_reason' => null,
                'notes' => 'Partial payment - first installment',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // Failed payments
            [
                'registration_number' => 'REG-2026-0010',
                'invoice_id' => 15,
                'amount' => 750000.00,
                'payment_method' => 'bank_transfer',
                'document_number' => 'TRF-2026-0007',
                'payment_date' => '2026-02-01',
                'receipt_file' => null,
                'status' => 'failed',
                'failure_reason' => 'Insufficient funds in account',
                'refund_date' => null,
                'refund_reason' => null,
                'notes' => 'Payment rejected by bank',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'registration_number' => 'REG-2026-0012',
                'invoice_id' => 24,
                'amount' => 500000.00,
                'payment_method' => 'bank_transfer',
                'document_number' => 'TRF-2026-0008',
                'payment_date' => '2026-01-21',
                'receipt_file' => null,
                'status' => 'failed',
                'failure_reason' => 'Invalid account number',
                'refund_date' => null,
                'refund_reason' => null,
                'notes' => 'Transfer failed - incorrect account details',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // Refunded payments
            [
                'registration_number' => 'REG-2026-0005',
                'invoice_id' => 5,
                'amount' => 500000.00,
                'payment_method' => 'bank_transfer',
                'document_number' => 'TRF-2026-0009',
                'payment_date' => '2026-01-14',
                'receipt_file' => null,
                'status' => 'refunded',
                'failure_reason' => null,
                'refund_date' => '2026-01-20',
                'refund_reason' => 'Student withdrew application',
                'notes' => 'Full refund processed due to application withdrawal',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'registration_number' => 'REG-2026-0008',
                'invoice_id' => null,
                'amount' => 1500000.00,
                'payment_method' => 'cash',
                'document_number' => 'CASH-2026-0003',
                'payment_date' => '2026-01-25',
                'receipt_file' => null,
                'status' => 'refunded',
                'failure_reason' => null,
                'refund_date' => '2026-01-30',
                'refund_reason' => 'Duplicate payment error',
                'notes' => 'Refunded due to accidental double payment',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // Additional paid payments
            [
                'registration_number' => 'REG-2026-0013',
                'invoice_id' => 16,
                'amount' => 500000.00,
                'payment_method' => 'bank_transfer',
                'document_number' => 'TRF-2026-0010',
                'payment_date' => '2026-02-04',
                'receipt_file' => null,
                'status' => 'paid',
                'failure_reason' => null,
                'refund_date' => null,
                'refund_reason' => null,
                'notes' => 'Law program registration fee',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'registration_number' => 'REG-2026-0017',
                'invoice_id' => 18,
                'amount' => 500000.00,
                'payment_method' => 'cash',
                'document_number' => 'CASH-2026-0004',
                'payment_date' => '2026-02-11',
                'receipt_file' => null,
                'status' => 'paid',
                'failure_reason' => null,
                'refund_date' => null,
                'refund_reason' => null,
                'notes' => 'Sports Science registration payment',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'registration_number' => 'REG-2026-0019',
                'invoice_id' => 19,
                'amount' => 500000.00,
                'payment_method' => 'bank_transfer',
                'document_number' => 'TRF-2026-0011',
                'payment_date' => '2026-02-07',
                'receipt_file' => null,
                'status' => 'paid',
                'failure_reason' => null,
                'refund_date' => null,
                'refund_reason' => null,
                'notes' => 'Environmental Science registration',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'registration_number' => 'REG-2026-0017',
                'invoice_id' => 22,
                'amount' => 2500000.00,
                'payment_method' => 'bank_transfer',
                'document_number' => 'TRF-2026-0012',
                'payment_date' => '2026-02-26',
                'receipt_file' => null,
                'status' => 'paid',
                'failure_reason' => null,
                'refund_date' => null,
                'refund_reason' => null,
                'notes' => 'Sports facility fee payment',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // More pending payments
            [
                'registration_number' => 'REG-2026-0011',
                'invoice_id' => 10,
                'amount' => 3500000.00,
                'payment_method' => 'bank_transfer',
                'document_number' => 'TRF-2026-0013',
                'payment_date' => '2026-02-02',
                'receipt_file' => null,
                'status' => 'pending',
                'failure_reason' => null,
                'refund_date' => null,
                'refund_reason' => null,
                'notes' => 'First installment for Economics tuition',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'registration_number' => 'REG-2026-0015',
                'invoice_id' => 17,
                'amount' => 500000.00,
                'payment_method' => 'bank_transfer',
                'document_number' => 'TRF-2026-0014',
                'payment_date' => '2026-01-29',
                'receipt_file' => null,
                'status' => 'pending',
                'failure_reason' => null,
                'refund_date' => null,
                'refund_reason' => null,
                'notes' => 'Biomedical Engineering registration - pending verification',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // Payments without invoice (direct payments)
            [
                'registration_number' => 'REG-2026-0016',
                'invoice_id' => null,
                'amount' => 250000.00,
                'payment_method' => 'cash',
                'document_number' => 'CASH-2026-0005',
                'payment_date' => '2026-01-31',
                'receipt_file' => null,
                'status' => 'paid',
                'failure_reason' => null,
                'refund_date' => null,
                'refund_reason' => null,
                'notes' => 'Textbook purchase payment',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'registration_number' => 'REG-2026-0018',
                'invoice_id' => null,
                'amount' => 500000.00,
                'payment_method' => 'cash',
                'document_number' => 'CASH-2026-0006',
                'payment_date' => '2026-02-01',
                'receipt_file' => null,
                'status' => 'paid',
                'failure_reason' => null,
                'refund_date' => null,
                'refund_reason' => null,
                'notes' => 'Uniform and materials payment',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'registration_number' => 'REG-2026-0020',
                'invoice_id' => null,
                'amount' => 300000.00,
                'payment_method' => 'bank_transfer',
                'document_number' => 'TRF-2026-0015',
                'payment_date' => '2026-02-02',
                'receipt_file' => null,
                'status' => 'paid',
                'failure_reason' => null,
                'refund_date' => null,
                'refund_reason' => null,
                'notes' => 'Student ID card and parking permit',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // More varied payments
            [
                'registration_number' => 'REG-2026-0002',
                'invoice_id' => 6,
                'amount' => 2500000.00,
                'payment_method' => 'bank_transfer',
                'document_number' => 'TRF-2026-0016',
                'payment_date' => '2026-02-02',
                'receipt_file' => null,
                'status' => 'pending',
                'failure_reason' => null,
                'refund_date' => null,
                'refund_reason' => null,
                'notes' => 'Partial tuition payment - first of three installments',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'registration_number' => 'REG-2026-0014',
                'invoice_id' => 25,
                'amount' => 500000.00,
                'payment_method' => 'bank_transfer',
                'document_number' => 'TRF-2026-0017',
                'payment_date' => '2026-02-01',
                'receipt_file' => null,
                'status' => 'pending',
                'failure_reason' => null,
                'refund_date' => null,
                'refund_reason' => null,
                'notes' => 'Hospitality Management registration - awaiting confirmation',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'registration_number' => 'REG-2026-0001',
                'invoice_id' => 11,
                'amount' => 750000.00,
                'payment_method' => 'bank_transfer',
                'document_number' => 'TRF-2026-0018',
                'payment_date' => '2026-02-02',
                'receipt_file' => null,
                'status' => 'pending',
                'failure_reason' => null,
                'refund_date' => null,
                'refund_reason' => null,
                'notes' => 'Partial payment for laboratory equipment fee',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'registration_number' => 'REG-2026-0019',
                'invoice_id' => 23,
                'amount' => 1500000.00,
                'payment_method' => 'bank_transfer',
                'document_number' => 'TRF-2026-0019',
                'payment_date' => '2026-02-02',
                'receipt_file' => null,
                'status' => 'pending',
                'failure_reason' => null,
                'refund_date' => null,
                'refund_reason' => null,
                'notes' => 'Partial payment for field research materials',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        // Use database builder to insert records
        $db = \Config\Database::connect();
        $builder = $db->table('payments');
        
        // Insert all records at once
        $builder->insertBatch($data);
        
        echo count($data) . " payment records have been seeded successfully!\n";
    }
}
